config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  post '/', to: 'toppages#create'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  # get 'edit/post', to: 'users#edit'
  
  resources :users, only: [:index, :show, :new, :create, :edit]
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  
  validates :shop_name, presence: true, length: { maximum: 50 }
  validates :congestion, presence: true
  validates :image, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
  
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :posts
  
  def feed_posts
    Post.where(user_id: self.post_ids + [self.id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.image.present?
      image_data = Magick::Image.read(@post.image.file.file)[0]
      exif_lat = image_data.get_exif_by_entry('GPSLatitude')[0][1].to_s.split(',').map(&:strip)
      exif_lng = image_data.get_exif_by_entry('GPSLongitude')[0][1].to_s.split(',').map(&:strip)
      @post.latitude = exif_lat.present? ? (Rational(exif_lat[0]) + Rational(exif_lat[1])/60 + Rational(exif_lat[2])/3600).to_f : nil
      @post.longitude = exif_lng.present? ? (Rational(exif_lng[0]) + Rational(exif_lng[1])/60 + Rational(exif_lng[2])/3600).to_f : nil
    end
    if @post.save
      flash[:success] = 'メッセージを投稿しました'
      redirect_to root_path
    else
      @posts = current_user.feed_posts.order('created_at DESC').page(params[:page])
      flash.now[:danger] = '投稿に失敗しました'
      render 'new'
    end
  end
  
  def seach
    latitude = params[:latitude]
    longitude = params[:longitude]
    
    @posts = Post.all.within(4, origin: [latitude, longitude])
  end
  
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    
    if @post.update(post_params)
      flash[:success] = '投稿が更新されました'
      redirect_to root_path
    else
      flash.now[:danger] = '投稿が更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    @post.destroy
    flash[:success] = 'メッセージを削除しました'
    redirect_to current_user
  end
  
  private
  
  def post_params
    params.require(:post).permit(:congestion, :shop_name, :image, :latitude, :longitude, :image_cache)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = 'ログインできました'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインできませんでした'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @post = current_user.posts.build

      #@hav_markers = Post.where.not(latitude: nil, longitude: nil)
      # @hash = Gmaps4rails.build_markers(@hav_markers) do |post, marker|
      #   marker.lat post.latitude
      #   marker.lng post.longitude
      #   marker.infowindow post.shop_name
      #   marker.json({title: post.address})
      # end
    end
  end
  
  def create
    # binding.pry
    @latitude = params[:latitude].to_f
    @longitude = params[:longitude].to_f
    @posts = []
    limit_time = Time.zone.now - 7200
    posts = Post.all
    posts.each do |post|
      post.latitude
      post.longitude
      p result = distance(post.latitude, post.longitude, @latitude, @longitude).to_f
      @posts << post if result < 4 && limit_time < post.created_at
    end
    # binding.pry
    @hav_markers = Post.where(id: @posts.pluck(:id)).where.not(latitude: nil, longitude: nil).order(created_at: :desc).to_a
    @hav_markers << Post.new(latitude: @latitude, longitude: @longitude, shop_name: "現在地")
    @hash = Gmaps4rails.build_markers(@hav_markers) do |post, marker|
      marker.lat post.latitude
      marker.lng post.longitude
      marker.infowindow post.shop_name
      marker.json({title: post.address})
    end
    
    render 'create', formats: 'js'
  end
  
  private
  
  def distance(lat1, lng1, lat2, lng2)
    # ラジアン単位に変換
    x1 = lat1.to_f * Math::PI / 180
    y1 = lng1.to_f * Math::PI / 180
    x2 = lat2.to_f * Math::PI / 180
    y2 = lng2.to_f * Math::PI / 180
    
    # 地球の半径 (km)
    radius = 6378.137
    
    # 差の絶対値
    diff_y = (y1 - y2).abs
    
    calc1 = Math.cos(x2) * Math.sin(diff_y)
    calc2 = Math.cos(x1) * Math.sin(x2) - Math.sin(x1) * Math.cos(x2) * Math.cos(diff_y)
    
    # 分子
    numerator = Math.sqrt(calc1 ** 2 + calc2 ** 2)
    
    # 分母
    denominator = Math.sin(x1) * Math.sin(x2) + Math.cos(x1) * Math.cos(x2) * Math.cos(diff_y)
    
    # 弧度
    degree = Math.atan2(numerator, denominator)
    
    # 大円距離 (km)
    return (degree * radius)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order('created_at DESC').page(params[:page])
    @hav_markers = @posts.where.not(latitude: nil, longitude: nil)
    @hash = Gmaps4rails.build_markers(@hav_markers) do |post, marker|
      marker.lat post.latitude
      marker.lng post.longitude
      marker.infowindow post.shop_name
      marker.json({title: post.address})
    end
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'ユーザ登録しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザ登録に失敗しました'
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update(post_params)
      flash[:success] = '投稿が更新されました'
      redirect_to @user
    else
      flash.now[:danger] = '投稿が更新されませんでした'
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def congestion_values
    { 
      0 => '混んでない',
      1 => '混んでる'
    }
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2018 HIRUMACHI</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">HIRUMACHI</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
          
          <% if false %>
            <li><%= link_to 'Users', users_path %></li>
          <% end %>
          
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'プロフィール', user_path(current_user), data: { turbolinks: false } %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
          <li><%= link_to '会員登録', signup_path %></li>
          <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="HIRUMACHIは現在位置から半径3km以内の飲食店の混雑状況を共有するアプリです" name="description">
    
    <title>Hirumachi</title>
    
    <%=favicon_link_tag %>
    
    <title>HIRUMACHI</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= yield :head %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <div class="desc">
        <h2>HIRUMACHIはあなたの半径3kmの飲食店の混み具合を共有できます！</h2>
      </div>
      
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/_form.html.erb
  <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@post) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :shop_name, '店舗名' %>
        <%= f.text_field :shop_name, class: 'form-control' %>
      </div>
        
      <div class="form-group">
        <%= f.label :congestion, '混み具合' %>
        <%= f.select :congestion, congestion_values.invert, {}, {class: 'form-control'} %>
      </div>
      
      <div class="form-group">
        <%= f.label :image, '店舗の写真' %>
        <%= image_tag @post.image.thumb.url if @post.image? %>
        <%= f.file_field :image %>
        <%= f.hidden_field :image_cache %>
      </div>
        
      <%= f.submit '投稿！', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<% if post.persisted? %>
  <li>
    <%= image_tag(post.image.thumb.url) if post.image.present? %><br>
    投稿時間 : <%= post.created_at.to_s(:time) %><br>
    <%= link_to congestion_values[post.congestion], post.user, class: "btn btn-#{ congestion_values[post.congestion] == "混んでる" ? "danger" : "success" }" %>
    店名 : <%= post.shop_name %><br>
    住所 : <%= post.address.present? ? post.address : "--取得に失敗しました--"%><br>
    <hr>
  </li>
<% end %>

app/views/posts/edit.html.erb
<div class="text-center">
  <h1>編集ページ</h1>
</div>
  
<%= render 'form', post: @post %>

<% if false %>
<%= link_to '投稿一覧', posts_path %>
<% end %>

app/views/posts/new.html.erb
<div class="text-center">
  <h1>投稿</h1>
</div>
  
<%= render 'form', post: @post %>

<%
=begin
%>
<%= link_to '投稿一覧', posts_path %>
<%
=end
%>

app/views/posts/show.html.erb
<h1><%= @post.id %></h1>

<p><%= @post.congestion %></p>

app/views/toppages/_map.html.erb
<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      <% if hash.present? && hash.count == 1 %>
        handler.getMap().setZoom(15);
      <% end %>
    });
</script>

app/views/toppages/_posts.html.erb
<ul><%= render posts %></ul>

app/views/toppages/create.js.erb
$('#map_wrapper').html('<%=j render 'map', hash: @hash %>');
$('#posts').html('<%=j render 'toppages/posts', posts: @hav_markers %>');

app/views/toppages/index.html.erb
<% if logged_in? %>
  <P>ログイン完了ユーザ: <%= current_user.name %></P>
  <div id="map" style='width: 500px; height: 300px;'></div>
  
  <div id='result'></div>
  <%= form_tag(root_path, method: :post, name: "gps", id: "gps", remote: true) do %>
    <%= hidden_field_tag "authenticity_token", form_authenticity_token %>
  
    <%= hidden_field_tag :latitude %>
    <%= hidden_field_tag :longitude %>
  
  <% submit_tag("post") %>
  <% end %>
  <script>
    // ユーザーの端末がGeoLocation APIに対応しているかの判定
    
    // 対応している場合
    if( navigator.geolocation )
    {
    	// 現在地を取得
    	navigator.geolocation.getCurrentPosition(
    
    		// [第1引数] 取得に成功した場合の関数
    		function( position )
    		{
    			// 取得したデータの整理
    			var data = position.coords ;
    
    			// データの整理
    			var lat = data.latitude ;
    			var lng = data.longitude ;
    
    			// アラート表示
    //			alert( "あなたの現在位置は、\n[" + lat + "," + lng + "]\nです。" ) ;
    
    			// HTMLへの書き出し
    			document.getElementById( 'result' ).innerHTML = '<br><dl><dt>現在地 : 緯度' + lat + ' 経度' + lng + '</dt></dl>';
          document.getElementById( 'latitude' ).value = lat;
          document.getElementById( 'longitude' ).value = lng;
          // document.gps.submit();
          $('#gps').submit();
    			// 位置情報
    			var latlng = new google.maps.LatLng( lat , lng ) ;

    			// Google Mapsに書き出し
    		// 	var map = new google.maps.Map( document.getElementById( 'map-canvas' ) , {
    		// 		zoom: 15 ,				// ズーム値
    		// 		center: latlng ,		// 中心座標 [latlng]
    		// 	} ) ;
    
    			// マーカーの新規出力
    		// 	new google.maps.Marker( {
    		// 		map: map ,
    		// 		position: latlng ,
    		// 	} ) ;
    		},

    		// [第2引数] 取得に失敗した場合の関数
    		function( error )
    		{
    			// エラーコード(error.code)の番号
    			// 0:UNKNOWN_ERROR				原因不明のエラー
    			// 1:PERMISSION_DENIED			利用者が位置情報の取得を許可しなかった
    			// 2:POSITION_UNAVAILABLE		電波状況などで位置情報が取得できなかった
    			// 3:TIMEOUT					位置情報の取得に時間がかかり過ぎた…
    
    			// エラー番号に対応したメッセージ
    			var errorInfo = [
    				"原因不明のエラーが発生しました…。" ,
    				"位置情報の取得が許可されませんでした…。" ,
    				"電波状況などで位置情報が取得できませんでした…。" ,
    				"位置情報の取得に時間がかかり過ぎてタイムアウトしました…。"
    			] ;
    
    			// エラー番号
    			var errorNo = error.code ;
    
    			// エラーメッセージ
    			var errorMessage = "[エラー番号: " + errorNo + "]\n" + errorInfo[ errorNo ] ;
    
    			// アラート表示
    			alert( errorMessage ) ;
    
    			// HTMLに書き出し
    			document.getElementById("result").innerHTML = errorMessage;
    		} ,
    
    		// [第3引数] オプション
    		{
    			"enableHighAccuracy": false,
    			"timeout": 8000,
    			"maximumAge": 2000,
    		}
    
    	) ;
    }
    
    // 対応していない場合
    else
    {
    	// エラーメッセージ
    	var errorMessage = "お使いの端末は、GeoLacation APIに対応していません。" ;
    
    	// アラート表示
    	alert( errorMessage ) ;
    
    	// HTMLに書き出し
    	document.getElementById( 'result' ).innerHTML = errorMessage ;
    }
  </script>

<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>HI RU MA CHI</h1>
      <%= link_to '会員登録', signup_path, class: 'btn  btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

<% content_for :head do %>
  <script src="//maps.google.com/maps/api/js?v=3&key=AIzaSyCktzdkvWZpHN-xQkqHGIdzw71gx1sfJDA"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<% end %>

<div id='map_wrapper'>
</div>

<ul id='posts'>
</ul>


<p><%= link_to '混み具合を報告', new_post_path, class: 'btn btn-primary btn-block'%></p>

app/views/users/_users.html.erb
<%
=begin
  <% if users.any? %>
    <ul class="media-list">
      <% users.each do |user| %>
        <li class="media">
          <div class="media-left">
            <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
          </div>
          <div class="media-body">
            <div>
              <%= user.name %>
            </div>
            <div>
              <p><%= link_to 'View profile', user_path(user) %></p>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
    <%= paginate users %>
  <% end %>
=end
%>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>編集ページ</h1>
</div>
  
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@post) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        
        <div class="form-group">
            <%= f.label :shop_name, '店舗名' %>
            <%= f.text_field :shop_name, class: 'form-control' %>
        </div>
          
        <div class="form-group">
          <%= f.label :congestion, '混み具合' %>
          <%= f.select :congestion, congestion_values.invert, {}, { class: 'form-control'}S %>
        </div>
        
        <div class="form-group">
        <%= f.label :image, '店舗の写真' %>
        <%= image_tag @post.imagethumb.url if @post.image? %>
        <%= f.file_field :image %>
        <%= f.hidden_field :image_cache %>
      </div>
          
        <%= f.submit '編集を完了する', class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
  </div>

<%
=begin
<%= link_to '投稿一覧', posts_path %>
=end
%>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>会員登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
    
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit '会員登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @user.name %></h3>
    </div>
    <div class="panel-body">
      <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 200}) %>" alt="">
    </div>
  </aside>

  <div class='col-xs-8'>
    <div id="map" style='width: 500px; height: 300px;'></div>
  </div>
</div>


<h2>投稿一覧</h2>
<div class="menu">
  <ul>
    <% @posts.each do |post| %>
      <li>
        <% if post.image? %>
          <%= image_tag post.image.thumb.url %>
        <% else %>
          <%= image_tag 'noimage.gif' %>
        <% end %>
        <div id="list">
          <%= post.shop_name %>: <%= congestion_values[post.congestion] %>
          <%= link_to '投稿を削除する', post, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

<p><%= link_to '混み具合を報告', new_post_path, class: 'btn btn-primary btn-block'%></p>


<% content_for :head do %>
  <script src="//maps.google.com/maps/api/js?v=3&key=AIzaSyCktzdkvWZpHN-xQkqHGIdzw71gx1sfJDA"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<% end %>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      <% if @hash.count == 1 %>
        handler.getMap().setZoom(15);
      <% end %>
    });
</script>